name: JAVA CI
on: push
env:
  docker_username: ${{ github.actor }}
  docker_password: ${{ secrets.GITHUB_TOKEN }}
  GIT_COMMIT: ${{ github.sha }}
jobs:
  Clone-down:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
    - name: Clone-down
      uses: actions/checkout@v3
    - name: Upload Repo
      uses: actions/upload-artifact@v3
      with:
        name: code
        path: .
  Build:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    needs: Clone-down
    steps:  
      - name: Download code
        uses: actions/download-artifact@v3
        with:
          name: code
          path: .  
      - name: "Build application"
        run: chmod +x ci/build-app.sh && ci/build-app.sh
      - name: "Unit test"
        run: ci/unit-test-app.sh
      - name: Upload a repository
        uses: actions/upload-artifact@v3
        with:
          name: repo-artifact
          path: .
      - name: Upload lib jar app
        uses: actions/upload-artifact@v3
        with:
          name: lib-app-artifat
          path: app/build/libs/app-0.1-all.jar
  Docker-image:
    runs-on: ubuntu-latest
    needs: [Build]
    permissions:
      packages: write
    steps:
      - name: Download code
        uses: actions/download-artifact@v3
        with: 
          name: repo-artifact
          path: .
      - name: build docker
        run: chmod +x ci/build-docker.sh && ci/build-docker.sh
      - name: push docker
        run: chmod +x ci/push-docker.sh && ci/push-docker.sh
  Component-test:
    runs-on: [self-hosted]
    needs: Docker-image
    steps:
    - name: Download code
      uses: actions/download-artifact@v3
      with: 
        name: repo-artifact
        path: .
    - name: Execute component test
      run: chmod +x ci/component-test.sh && ci/component-test.sh
  Performance-test:
    runs-on: ubuntu-latest
    needs: Docker-image
    steps:
    - name: Download code
      uses: actions/download-artifact@v3
      with: 
        name: repo-artifact
        path: .
    - name: Execute performance test
      run: chmod +x ci/performance-test.sh && ci/performance-test.sh
  