name: workflow-with-container
on: push
jobs:
  Build:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:    
      - name: Clone-down
        uses: actions/checkout@v3
      - name: "Build application"
        run: chmod +x ci/build-app.sh && ci/build-app.sh
      - name: "Unit test"
        run: ci/unit-test-app.sh
      - name: Upload a repository
        uses: actions/upload-artifact@v3
        with:
          name: repo-artifact
          path: .